version: "3"

services:
  webui: 
    build: "./artifacts/angular/"
    container_name: gtui1
    restart: always
    ports:
      - "8080:80"
      - "444:443"
    depends_on: 
      - webserver
    links:
      - webserver

  webserver: 
    build: "./artifacts/webapi/"
    container_name: gtweb1
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - db
    links:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: gtsql1
    environment:
      - SA_PASSWORD=31Freeble$$
      - ACCEPT_EULA=Y
      - MSSQL_PID=Standard
    ports:
      - "1433:1433"
